### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by nimdeveloper** [fzn0x/mazer-nuxt#161]
- Components are inside directory named `Layouts`, and their usage [(ex)](https://github.com/bl0cknumber/mazer-nuxt/blob/master/layouts/default.vue#L4) is incorrect. add inner directory name to nuxt.config.js or change them to use directories
- Adding event listeners to not exists elements causes error [(here)](https://github.com/bl0cknumber/mazer-nuxt/blob/master/components/Layouts/Sidebar.vue#L82) (actually, this event listeners is for VerticalHeader component)
- annoying warnings : ` Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`, `Recommendation: math.div($input-padding-y, 2) or calc($input-padding-y / 2)`

**Comment by bl0cknumber** [comment]
Thanks for reporting the issue! any pull request accepted too :)

**Comment by fzn0x** [comment]
This will be fixed by https://github.com/fzn0x/mazer-nuxt/pull/283
