### ISSUE TITLE
npm build not working

### ISSUE THREAD

**Issue by kconde2** [fzn0x/mazer-nuxt#246]
![npm build output](https://user-images.githubusercontent.com/43377621/177458586-71d74f5d-ebd6-414f-b66c-7adb4c4c4ac8.png)

**Comment by kconde2** [comment]
![npm build output](https://user-images.githubusercontent.com/43377621/177458586-71d74f5d-ebd6-414f-b66c-7adb4c4c4ac8.png)

**Comment by fzn0x** [comment]
Hi, kindly specify the steps you are doing during the development.

**Comment by fzn0x** [comment]
This will be fixed by #283
