### ISSUE TITLE
Bug: flickering dark mode

### ISSUE THREAD

**Issue by fzn0x** [fzn0x/mazer-nuxt#295]
We encounter the same issue as https://github.com/zuramai/mazer/pull/130

But this is harder to find a workaround

**Comment by WailanTirajoh** [comment]
i'll try to solve this issue, i think its because the dark mode component run on client side so it got flickering when the component hydrate to the dom html.

**Comment by fzn0x** [comment]
After https://github.com/fzn0x/mazer-nuxt/commit/80741b5af39d927f31fe29baa357a20f4913a5d2 merged, just need to add one more fix, try to refresh the page you will see that the flash still exist, since we store the theme inside localStorage, hacks will be to create a script that loads just before everything

**Comment by WailanTirajoh** [comment]
I think we need to include "https://github.com/zuramai/mazer/blob/main/src/assets/js/initTheme.js" script like the mazer does.
